#
# Main Dockerfile for Developing Code
#
# Should create small images < 30MB :)
#
FROM golang:1.8.3-alpine
LABEL maintainer "james.tarball@newtonsystems.co.uk"

ENV REPO_DIR /go/src/github.com/newtonsystems/agent-mgmt

WORKDIR $REPO_DIR

RUN apk add --update --virtual .build-deps \
        swatch \
        bash \
        curl \
        ncurses \
        build-base \
        git \
        musl-dev \
        linux-headers \
        make \
        gcc \
        g++ \
        autoconf \
        automake \
        libtool \
        inotify-tools \
    && rm -rf /var/cache/apk/*

# Add Label Badges to Dockerfile powered by microbadger
ARG VCS_REF
LABEL org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="e.g. https://github.com/microscaling/microscaling"

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

ENTRYPOINT ["make", "serve-fast"]
